### PR TITLE
Feature toggles

### PR DESCRIPTION
**Pull request by yawn**
Dependencies & turning them on / off works as expected. If there is no additional feedback I'd build them into `superwerker.yaml` (defaults to `true`).

Try it out by calling `components/dev.yaml` first, then `components/dev-main.yaml` and toggle its flippers in the pseudo shebang.

### CODE REVIEW

**Comment by yawn** [comment]
Proposal for next decoupling steps:

- merge / adopt feature toggles for main and give GD & SH dependencies on CT
- provide lambda function to create random email address that serves as SES delegation healthcheck as well (timeout + error) - combined with a pseudo null default value for the CT email parameters this can auto-generated / healthcheck the rootemail stack unless explicitly overridden with email addresses not from rootemails

**Review by s0enke — CHANGES_REQUESTED** [review]
Examples look good. Not sure whether we need the examples as code?
For me it would be OK to start right ahead with real feature flags / conditions in `superwerker.yaml` 

Edit: I just saw the comment:
> If there is no additional feedback I'd build them into superwerker.yaml

Yes please go ahead :)

**Comment by yawn** [comment]
Have another look please, specifically at my `dev*` comments. I think I'd create a `/dev/` folder under components and put a hello world template there?

**Review by s0enke — CHANGES_REQUESTED** [review]
LGTM, but there are conflicts. I would suggest to decouple the renaming of xx-rootmail (can be done in master directly imo). Off-topic: I would simply drop the `xx-` prefixes, since ordering can change. Its' more a historical idea.

**Comment by yawn** [comment]
Rebased and dropped prefixes.

**Comment by yawn** [comment]
Regarding `/dev/` - do you agree to commit this?

**Comment by yawn** [comment]
Merge please @s0enke

**Pull request merged**
