### PR TITLE
feat: add github templates 

### PR DESCRIPTION
**Pull request by mavogel**
- for issues
- moved PR template

## Definition of done (v0.0.1)

- [ ] Automated integration test
- [ ] Integrity protection according to ADR-NNNN
- [ ] Structured Logging and Monitoring for Lambda function according to ADR-NNNN

### CODE REVIEW

**Comment by sbstjn** [comment]
What do you think about my changes?

Let's just have a template for "Bugs" in issues and try to force people to use Discussions for everything else.

**Comment by sbstjn** [comment]
Additionally, all new issues get a `pending` label.

**Comment by sbstjn** [comment]
Clicking the "New Issue" button will then look like this:

https://github.com/sbstjn/cdk-template/issues/new/choose

**Comment by sbstjn** [comment]
I created a Discussion for more details:

https://github.com/superwerker/superwerker/discussions/161

**Comment by mavogel** [comment]
LGTM :) as said in #161 as well

**Comment by s0enke** [comment]
Was adding a dummy SECURITY.md intended?

**Comment by s0enke** [comment]
@mavogel @sbstjn I assume moving the `pull_request_template.md`  broke the workflow which uses the PR template for new PRs? At least the template is not shown any more when creating a new PR.

Could you please revert/investigate this?

**Comment by s0enke** [comment]
@mavogel @sbstjn Was adding a dummy SECURITY.md intended? I'd rather have no documentation than wrong/confusing/dummy docs :)

**Comment by sbstjn** [comment]
I'll check this after lunch today. Thanks for the notice.

**Comment by sbstjn** [comment]
fixed.

**Pull request merged**
