### PR TITLE
Fixed root mail generation bug

### PR DESCRIPTION
**Pull request by jayanthkriyaraju**
## Definition of done (v0.0.1)

- [ ] Automated integration test
- [ ] Integrity protection according to ADR-NNNN
- [ ] Structured Logging and Monitoring for Lambda function according to ADR-NNNN

### CODE REVIEW

**Comment by s0enke** [comment]
Thanks!

Could you provide a test for the HTML mails? Esp. I am not sure why `img` tags are filtered out, but not other HTML tags.

**Comment by jayanthkriyaraju** [comment]
I filtered the img tag because with the image tag we were not getting the complete password reset link in the ops center.

I have attached the emails, before and after filtering img tag
Screenshot 2020-11-25 at 08 57 15
Screenshot 2020-11-25 at 08 57 00

**Comment by yawn** [comment]
I think we should not work selectively around HTML elements when the real issue is the total length of the body.

**Comment by sbstjn** [comment]
Fixed by #100

**Pull request closed without merging**
